name: Publish Docs
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npx typedoc --theme ./node_modules/typedoc-deno-theme/ index.d.ts
      - run: mv docs docs.new
      - run: git fetch --depth=1 origin gh-pages
      - run: git checkout gh-pages
      - run: rm -rf docs
      - run: mv docs.new docs
      - run: rm -f stamp
      - run: date > stamp.txt
      - run: cp CNAME docs/
      - run: git add docs stamp.txt
      - run: git config --global user.name 'GitHub Actions'
      - run: git config --global user.email 'actions@github.com'
      - run: git commit -m "docs: Deploy $GITHUB_SHA"
      - run: git push origin gh-pages
      - run: git checkout main
